version: '3.8'

services:
  spark-master:
    image: spark:4.0.0-scala2.13-java21-ubuntu
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "spark-master"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark-data:/data
      - spark-samples:/samples

  spark-worker:
    image: spark:4.0.0-scala2.13-java21-ubuntu
    container_name: spark-worker
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"
    volumes:
      - spark-data:/data
      - spark-samples:/samples

  spark-history:
    image: spark:4.0.0-scala2.13-java21-ubuntu
    container_name: spark-history
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/tmp/spark-events
    ports:
      - "18080:18080"
    volumes:
      - spark-events:/tmp/spark-events
      - spark-data:/data
      - spark-samples:/samples

volumes:
  spark-events:
  spark-data:
  spark-samples:
  spark-logs:
    driver: local
    driver_opts:
      type: none
      device: /var/log/spark
      o: bind
